name: Dependency Updates

on:
  schedule:
    - cron: '0 8 * * MON'  # Every Monday at 8 AM UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Update Backend Dependencies
        run: |
          if [ -d "cloud-backend" ]; then
            cd cloud-backend
            npm update
            npm audit fix --force || true
          fi

      - name: Update Mobile App Dependencies
        run: |
          if [ -d "mobile-app" ]; then
            cd mobile-app
            npm update
            npm audit fix --force || true
          fi

      - name: Check for Arduino Library Updates
        run: |
          echo "Checking for Arduino library updates..."
          # This would typically check for library updates
          # and create notifications for manual review

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Automated Dependency Updates'
          body: |
            ## Automated Dependency Updates

            This PR contains automated dependency updates:
            - Backend dependencies updated
            - Mobile app dependencies updated
            - Security vulnerabilities addressed

            Please review and test before merging.

            Generated by GitHub Actions
          branch: dependency-updates
          delete-branch: true

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Audit Backend Dependencies
        run: |
          if [ -d "cloud-backend" ]; then
            cd cloud-backend
            npm audit --audit-level=moderate
          fi

      - name: Audit Mobile App Dependencies
        run: |
          if [ -d "mobile-app" ]; then
            cd mobile-app
            npm audit --audit-level=moderate
          fi

      - name: Run SAST Scanner
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
